### ISSUE TITLE
[3.3.5]worldserver can`t be build.

### ISSUE THREAD

**Issue by errorcat** [TrinityCore/TrinityCore#19302]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

worldserver can`t be build using VS2015 with 3.3.5 newest codes

**Current behaviour:**

pull newest code 3.3.5 and build in VS2015
`8>------ Build started: Project: worldserver, Configuration: Release x64 ------
8>scripts.lib(eastern_kingdoms_script_loader.obj) : error LNK2019: unresolved external symbol "void __cdecl AddSC_boss_apothecary_hummel(void)" (?AddSC_boss_apothecary_hummel@@YAXXZ) referenced in function "void __cdecl AddEasternKingdomsScripts(void)" (?AddEasternKingdomsScripts@@YAXXZ)
8>D:\server\wow\tc335\build\bin\Release\worldserver.exe : fatal error LNK1120: 1 unresolved externals
========== Build: 7 succeeded, 1 failed, 14 up-to-date, 1 skipped ==========`

**Expected behaviour:**

should no failed

**Steps to reproduce the problem:**

1. fix this error ?

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Newest for now

**TDB version:** Newest for now
**Operating system:** Win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by TrinityCoreBot** [comment]
This issue is not considered valid because of the following reasons:
- No proper commit hash (revision)

Please read http://bit.ly/tc-issuetracker-and-you and add the missing information to **this issue**. Thanks.

**Comment by nawuko** [comment]
Looks like you forgot to re-run cmake.

**Comment by jackpoz** [comment]
You can see at https://github.com/TrinityCore/TrinityCore/commits/3.3.5 that AppVeyor successfully built the commits which usually means the issue happens only at your side.
As @nawuko said, linking errors like that happen when a new file is added, re-run cmake, rebuild the sources and this issue will be fixed.
Since it's an issue related to just your installation, please ask more questions on the forum.

**Comment by errorcat** [comment]
thanks all.I rebuild cmake.problem solved.
