### ISSUE TITLE
7.1.5 build failed

### ISSUE THREAD

**Issue by madmax765** [TrinityCore/TrinityCore#19426]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Build failed 
25>LINK : fatal error LNK1181: cannot open input file '..\game\Release\game.lib'
CHANGEME Description of the problem or issue here.

**Current behaviour:**
aprile 1st i can compile ok, but get failed on Commits on Apr 6, 2017 
CHANGEME Tell us what happens.

**TC rev. hash/commit:** 
d20dedebd6a322e1204fa911b4a2ddc7e2c3e67a

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS
windows 10
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by TrinityCoreBot** [comment]
This issue is not considered valid because of the following reasons:
- No proper commit hash (revision)

Please read http://bit.ly/tc-issuetracker-and-you and add the missing information to **this issue**. Thanks.

**Comment by jcmillions** [comment]
Yeah, the build is failing right now. As far as I know it started failing after https://github.com/TrinityCore/TrinityCore/commit/2a8294031b9ec73f1f082bd0137d9431545808ff

**Comment by DJBoxer** [comment]
@jcmillions those spellcons have been resolved if you do next 3 commits after.

Lastest commit I don't believe is finished [d20dede] that one is throwing few errors my end(https://github.com/TrinityCore/TrinityCore/commit/d20dedebd6a322e1204fa911b4a2ddc7e2c3e67al)

@madmax765 you list no info. Also no Logs your issue will be closed shortly due to not following template.

**Comment by Shauren** [comment]
Build is intentionally broken - work on 7.2 started so you can't use it with 7.1.5 anymore but not enough is done to enable 7.2 fully

**Comment by jcmillions** [comment]
@Shauren Take your time of course. TrinityCore has surprisingly stayed up to date with the latest build until now and many fixes have been added.

**Comment by liszt** [comment]
As a suggestion, it may be helpful to add a note to the commit that the build was intentionally broken while the update, feature or whatever progresses.  It might avoid wasting time on tickets like this as well as people trying to find out how to fix the "issue".  Looking at the auto build tools would tell you that a build is broken but not necessarily that it was intentional.

**Comment by jcmillions** [comment]
I noticed this error on appveyor
C:\projects\trinitycore\src\server\game\Spells\SpellMgr.cpp(2927): error C2039: 'ActiveIconID': is not a member of 'SpellInfo'
I was getting this issue before the 7.2 updates
