### ISSUE TITLE
Can't compile with GCC 5.1

### ISSUE THREAD

**Issue by durotar** [TrinityCore/TrinityCore#14840]
Trinity Core 3.3.5 rev. 43ae8727ace4
S.O. Arch Linux
Cmake 3.2
Boost 1.58.0
OpenSSL 1.0.2.a
MariaDB 10.0.18
GCC 5.1
Error log: http://pastebin.com/J8JYf7Ks

It says: "undefined reference to" many times

I compiled "the same rev" 1 or 2 a week ago with gcc 4.9 and it compiled without problems
then... support with gcc 5.1 will be necessary

**Comment by Vincent-Michael** [comment]
try D_GLIBCXX_USE_CXX11_ABI=1 to set

**Comment by durotar** [comment]
ty VM but I still have the same error...
I also tried with -DCMAKE_C_FLAGS=-std=gnu99 but nothing.

**Comment by Aokromes** [comment]
#14655
