### PR TITLE
Fix build failing since https://github.com/TrinityCore/TrinityCore/commit/52758c1a0b8e37e198d744803460e34600d115b5

### PR DESCRIPTION
**Pull request by Rochet2**
Fix build failing since https://github.com/TrinityCore/TrinityCore/commit/52758c1a0b8e37e198d744803460e34600d115b5

```
/TrinityCore/src/server/game/Maps/Map.cpp:2448:22: fatal error: 
      variable 'areaId' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
        if (GridMap* gmap = const_cast<Map*>(this)->GetGrid(x, y))
```

### CODE REVIEW

**Comment by tkrokli** [comment]
:+1: Good point, I was wondering why non-related files caused my latest PR to fail. :shipit:

**Comment by Keader** [comment]
Same? ff45a422c5e525c4d9465e91200803ffa95700d2

**Comment by tkrokli** [comment]
Yes, but ff45a42 is on 3.3.5 and we need the same warning fix here on 6.x too.
