### PR TITLE
Build/Boost: update Boost API to match version 1.66

### LINKED ISSUE #21171: Build/Boost: compile error on OSX (Mac)
**Description:**
Compiling on mac osx is not working

**Current behaviour:**

When i compile i get this error

```
/Users/andrea/WoW/Trinitycore/src/common/Utilities/AsioHacksImpl.h:25:44: fatal error: incomplete type 'boost::asio::io_service' named in nested name specifier
    class AsioStrand : public boost::asio::io_service::strand
                              ~~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /Users/andrea/Trinitycore/src/common/Logging/Log.cpp:1:
In file included from /Users/andrea/Trinitycore/build/src/common/Release/cotire/common_CXX_prefix.hxx:4:
In file included from /Users/andrea/Trinitycore/build/src/common/Release/cotire/common_CXX_prefix.cxx:4:
In file included from /Users/andrea/Trinitycore/src/common/PrecompiledHeaders/commonPCH.h:7:
/Users/andrea/Trinitycore/src/common/Logging/Log.h:38:15: note: forward declaration of 'boost::asio::io_service'
        class io_service;
              ^
1 error generated.
```

**Expected behaviour:**
It should not give errors 

**Steps to reproduce the problem:**

1. Follow the wiki
2. Run xcodebuild -target install -config Release

**Branch(es):**

Tested only in master, but i think both

**TC rev. hash/commit:** 
78ba1d76ddc65add3be3ccbb08c750c6a5c8f5a5

**TDB version:**  
N/A

**Operating system:** 
MacOSX 10.13.2 
Xcode 9.2
Homebrew

### PR DESCRIPTION
**Pull request by dimiandre**
**Changes proposed:**
This enable build with boost 1.66 (and broke build with <= 1.65)

**Target branch(es):** 
- [x] master

**Issues addressed:** 
Closes #21171 

**Tests performed:** 
Build on MacOSX, Login in the game

**Known issues and TODO list:** (add/remove lines as needed)
get_io_service() is deprected, but i don't know how to cast get_executor to the proper type

### CODE REVIEW

**Comment by Shauren** [comment]
We are NOT dropping pre 1.66 versions.

**Comment by Shauren** [comment]
But I am going to use this PR anyway with a bunch of preprocessor conditions

**Comment by dimiandre** [comment]
thanks, i never used preprocessors so i was not confident to push it

**Comment by jackpoz** [comment]
@Shauren boost 1.66 is still backward compatible allowing to use the old typedef io_service instead of io_context, there's no need for TC to add any preprocessor definition

**Comment by Shauren** [comment]
@jackpoz its only a matter of time before that backward compatibility is removed and doing the same as we already did with Optional will also allow to switch to `std::` in future
