### ISSUE TITLE
[3.3.5a][linux] fatal-error in make

### ISSUE THREAD

**Issue by Albirew** [TrinityCore/TrinityCore#22785]
**Description:**

Cannot build with latest commit (c16d461)

**Current behaviour:**

make outputs a fatal error then exit 1
```
[ 18%] Building CXX object src/server/shared/CMakeFiles/shared.dir/enuminfo_SharedDefines.cpp.o
/*OCCULTED*/TrinityCore/src/server/shared/enuminfo_SharedDefines.cpp:27:79: error: specialization of ‘template<class Enum> static EnumText Trinity::Impl::EnumUtils<Enum>::ToString(Enum)’ in different namespace [-fpermissive]
 TC_API_EXPORT EnumText Trinity::Impl::EnumUtils<Powers>::ToString(Powers value

compilation terminated due to -Wfatal-errors.
src/server/shared/CMakeFiles/shared.dir/build.make:77 : la recette pour la cible « src/server/shared/CMakeFiles/shared.dir/enuminfo_SharedDefines.cpp.o » a échouée
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/enuminfo_SharedDefines.cpp.o] Erreur 1
make[2]: *** Attente des tâches non terminées....
CMakeFiles/Makefile2:1231 : la recette pour la cible « src/server/shared/CMakeFiles/shared.dir/all » a échouée
make[1]: *** [src/server/shared/CMakeFiles/shared.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```
Also, may not be related but this warning showed up when compiling:
```
[ 14%] Building CXX object src/common/CMakeFiles/common.dir/Debugging/Errors.cpp.o
/*OCCULTED*/TrinityCore/src/common/Debugging/Errors.cpp:44:38: warning: ‘TrinityAssertionFailedMessage’ initialized and declared ‘extern’
 extern "C" TC_COMMON_API char const* TrinityAssertionFailedMessage = nullptr;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Expected behaviour:**

Compilation working seamlessly

**Steps to reproduce the problem:**

0. cd ${TrinityRoot}/TrinityCore/
1. git pull origin 3.3.5
2. cd build/
3. cmake ../ -DCMAKE_INSTALL_PREFIX=${TrinityRoot}/server -DCONF_DIR=${TrinityRoot}/server/etc -DTOOLS=1 -DSCRIPTS="dynamic" -DWITH_WARNINGS=1
4. make -j $(nproc)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c16d461e16f0 2018-11-11 17:52:41 +0100 (3.3.5 branch)
(as written in build/revision_data.h)

**Operating system:** 

Debian GNU/Linux 9.6 (stretch) x86_64

**Comment by Albirew** [comment]
forgot to mention this but build directory is always cleaned before trying to build:
```bash
#!/bin/bash
TrinityRoot=/*OCCULTED*
cd ${TrinityRoot}/TrinityCore/
git pull origin 3.3.5
cd build/
make clean
rm -rf *
cmake ../ -DCMAKE_INSTALL_PREFIX=${TrinityRoot}/server -DCONF_DIR=${TrinityRoot}/server/etc -DTOOLS=1 -DSCRIPTS="dynamic" -DWITH_WARNINGS=1
make -j $(nproc)
if [ "$?" -ne "0" ]; then
  echo -e "\033[0;31mERROR DURING MAKE\033[1;37m: terminating script."
  exit 1
fi
```

**Comment by Aokromes** [comment]
TrinityCore rev. c16d461e16f0 2018-11-11 17:52:41 +0100 (3.3.5 branch) (Unix, None, Static) (worldserver-daemon) ready...

cannot reproduce... maybe you have custom code? ps also travis shows compile working.

**Comment by Albirew** [comment]
no custom code, I use what's pulled from github without editing, maybe related to dynamic linking?

**Comment by Shauren** [comment]
what compiler?

**Comment by Aokromes** [comment]
nope, not dynamic thing:

[100%] Built target worldserver

clang 8.0.0

**Comment by Albirew** [comment]
The C compiler identification is GNU 6.3.0
GNU Make 4.1
cmake version 3.7.2
Boost version: 1.62.0
TrinityCore buildtype  : RelWithDebInfo

tried `git fetch --all` and `git reset --hard origin/3.3.5`, still get stuck on same error at build.
Tried with removing `-DSCRIPTS="dynamic"` (static linking), getting same error.
```make
src/server/shared/enuminfo_SharedDefines.cpp:27:79: error: specialization of ‘template<class Enum> static EnumText Trinity::Impl::EnumUtils<Enum>::ToString(Enum)’ in different namespace [-fpermissive]
 TC_API_EXPORT EnumText Trinity::Impl::EnumUtils<Powers>::ToString(Powers value
```

**Comment by Shauren** [comment]
Works with GCC 7.3.0
Just in case, try this https://gist.github.com/Shauren/957039da4efc79f7df6153eca7d43612 (i fully expect it to fail later in build, just need to know if that specific file, enuminfo_SharedDefines.cpp, passes)

**Comment by Albirew** [comment]
Still building but I see quite a lot of warnings like these:
```make
[ 23%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartAI.cpp.o
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:22:0,
                 from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.cpp:18:
/*OCCULTED*/TrinityCore/src/server/game/AI/CreatureAI.h:128:22: warning: ‘virtual void CreatureAI::SpellHit(GameObject*, const SpellInfo*)’ was hidden [-Woverloaded-virtual]
         virtual void SpellHit(GameObject* /*caster*/, SpellInfo const* /*spellInfo*/) { }
                      ^~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.cpp:18:0:
/*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:104:14: warning:   by ‘virtual void SmartAI::SpellHit(Unit*, const SpellInfo*)’ [-Woverloaded-virtual]
         void SpellHit(Unit* unit, SpellInfo const* spellInfo) override;
              ^~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:22:0,
                 from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.cpp:18:
/*OCCULTED*/TrinityCore/src/server/game/AI/CreatureAI.h:132:22: warning: ‘virtual void CreatureAI::SpellHitTarget(GameObject*, const SpellInfo*)’ was hidden [-Woverloaded-virtual]
         virtual void SpellHitTarget(GameObject* /*target*/, SpellInfo const* /*spellInfo*/) { }
                      ^~~~~~~~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.cpp:18:0:
/*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:107:14: warning:   by ‘virtual void SmartAI::SpellHitTarget(Unit*, const SpellInfo*)’ [-Woverloaded-virtual]
         void SpellHitTarget(Unit* target, SpellInfo const* spellInfo) override;
              ^~~~~~~~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:23:0,
                 from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.cpp:18:
/*OCCULTED*/TrinityCore/src/server/game/AI/CoreAI/GameObjectAI.h:90:22: warning:  virtual void GameObjectAI::SpellHit(GameObject*, const SpellInfo*)’ was hidden  -Woverloaded-virtual]
         virtual void SpellHit(GameObject* /*caster*/, SpellInfo const* /*spellInfo*/) { }
                      ^~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.cpp:18:0:
/*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:271:14: warning:   by ‘virtual void SmartGameObjectAI::SpellHit(Unit*, const SpellInfo*)’ [-Woverloaded-virtual]
         void SpellHit(Unit* unit, SpellInfo const* spellInfo) override;
              ^~~~~~~~
[ 23%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartScript.cpp.o
In file included from /*OCCULTED*/TrinityCore/src/server/game/Grids/Notifiers/GridNotifiers.h:24:0,
                 from /*OCCULTED*/TrinityCore/src/server/game/Texts/CreatureTextMgrImpl.h:24,
                 from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartScript.cpp:23:
/*OCCULTED*/TrinityCore/src/server/game/AI/CreatureAI.h:128:22: warning: ‘virtual void CreatureAI::SpellHit(GameObject*, const SpellInfo*)’ was hidden [-Woverloaded-virtual]
         virtual void SpellHit(GameObject* /*caster*/, SpellInfo const* /*spellInfo*/) { }
                      ^~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartScript.cpp:37:0:
/*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:104:14: warning:   by ‘virtual void SmartAI::SpellHit(Unit*, const SpellInfo*)’ [-Woverloaded-virtual]
         void SpellHit(Unit* unit, SpellInfo const* spellInfo) override;
              ^~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/Grids/Notifiers/GridNotifiers.h:24:0,
                 from /*OCCULTED*/TrinityCore/src/server/game/Texts/CreatureTextMgrImpl.h:24,
                 from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartScript.cpp:23:
/*OCCULTED*/TrinityCore/src/server/game/AI/CreatureAI.h:132:22: warning: ‘virtual void CreatureAI::SpellHitTarget(GameObject*, const SpellInfo*)’ was hidden [-Woverloaded-virtual]
         virtual void SpellHitTarget(GameObject* /*target*/, SpellInfo const* /*spellInfo*/) { }
                      ^~~~~~~~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartScript.cpp:37:0:
/*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:107:14: warning:   by ‘virtual void SmartAI::SpellHitTarget(Unit*, const SpellInfo*)’ [-Woverloaded-virtual]
         void SpellHitTarget(Unit* target, SpellInfo const* spellInfo) override;
              ^~~~~~~~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:23:0,
                 from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartScript.cpp:37:
/*OCCULTED*/TrinityCore/src/server/game/AI/CoreAI/GameObjectAI.h:90:22: warning:  virtual void GameObjectAI::SpellHit(GameObject*, const SpellInfo*)’ was hidden  -Woverloaded-virtual]
         virtual void SpellHit(GameObject* /*caster*/, SpellInfo const* /*spellInfo*/) { }
                      ^~~~~~~~
In file included from /*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartScript.cpp:37:0:
/*OCCULTED*/TrinityCore/src/server/game/AI/SmartScripts/SmartAI.h:271:14: warning:   by ‘virtual void SmartGameObjectAI::SpellHit(Unit*, const SpellInfo*)’ [-Woverloaded-virtual]
         void SpellHit(Unit* unit, SpellInfo const* spellInfo) override;
              ^~~~~~~~
```
(and so on)
Oh, and this one popped too:
```make
[ 26%] Building CXX object src/server/game/CMakeFiles/game.dir/Conditions/DisableMgr.cpp.o
/*OCCULTED*/TrinityCore/src/server/game/Conditions/DisableMgr.cpp: In function ‘void DisableMgr::LoadDisables()’:
/*OCCULTED*/TrinityCore/src/server/game/Conditions/DisableMgr.cpp:100:37: warning: comparison is always false due to limited range of data type [-Wtype-limits]
                 if (!flags || flags > MAX_SPELL_DISABLE_TYPE)
                               ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jackpoz** [comment]
you see the warnings because of -DWITH_WARNINGS=1 (they should be fixed ofc, just saying)
