### ISSUE TITLE
[3.3.5] Updater reapplies 'old' sqls

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#16209]
Core hash: 1d9d03b2891b5481eff6541a8563599ccc60c48d
TDB: 335.60

OS: `CentOS release 6.7 (Final)`
GCC: `gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)`

World initialization fails after supposed hash change (which isn't the case)

```
Updating World database...
>> Reapplying update "2015_07_14_00_world.sql" '70FAC1E' -> '0D0E479' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_14_01_world_335.sql" 'E70FF25' -> '2C5DD55' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_14_02_world.sql" 'C61753B' -> 'F71EB21' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_14_03_world.sql" '2934846' -> 'B856ABF' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_14_04_world.sql" '6CB039A' -> 'AAA7094' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_14_05_world.sql" 'D1E5B17' -> 'A997651' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_15_00_world.sql" '5BF09C7' -> 'EBC6BE7' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_15_01_world.sql" 'C68BCD6' -> '494F6AC' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_15_02_world.sql" 'CC11831' -> 'BA085E4' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_16_00_world.sql" '97B99B5' -> '494AC8B' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_17_00_world.sql" '9E8CE7B' -> '80CD5DD' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_17_01_world.sql" '3A43E12' -> 'AE45FFF' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_17_02_world.sql" '9044232' -> '26B3772' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_17_03_world.sql" '958FC60' -> '755DE6D' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_17_04_world.sql" '672C450' -> '10C07A8' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_18_00_world.sql" '086552F' -> '6C5AB36' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_18_01_world.sql" 'CB80375' -> 'D9C8098' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Reapplying update "2015_07_19_00_world_2015_07_18_04.sql" 'C379ABE' -> '21FCDC6' (it changed)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 14: Table 'world.locales_gameobject' doesn't exist

Applying of file '/home/serv/dev/sql/old/3.3.5a/world/59_2015_11_07/2015_07_19_00_world_2015_07_18_04.sql' to database 'world' failed! If you are an user pull the latest revision from the repository. If you are a developer fix your sql query.
Could not update the World database, see log for details.
```

**Comment by tkrokli** [comment]
TrinityCore rev. e5d4005cc6f4 2016-01-08 00:10:15 +0100 (3.3.5 branch) (Win64, Release)
Can't replicate issue. I always only get the updates after last compile, never any 335.59 updates.
```
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 8 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 12 archived updates.
Updating World database...
>> Applying update "2016_01_07_00_world.sql" 'DEEC349'...
Warning: Using a password on the command line interface can be insecure.

>> Applying update "2016_01_07_01_world.sql" '725542F'...
Warning: Using a password on the command line interface can be insecure.

>> Applying update "2016_01_07_02_world.sql" 'FC53E79'...
Warning: Using a password on the command line interface can be insecure.

>> Applying update "2016_01_08_00_world.sql" 'A40EA4B'...
Warning: Using a password on the command line interface can be insecure.

>> Applied 4 queries. Containing 89 new and 882 archived updates.
Realm running as realm ID 1
Using World DB: TDB 335.60
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
```
Also empty world DB to let worldserver insert full TDB 335.60, as well as updates, works just fine.

It is almost as if you had got the full TDB 335.59 SQL dump in your core folder or something else triggering the use of 335.59 instead of TDB 335.60, but I have no idea of exactly what goes on there.

**Comment by DDuarte** [comment]
Does `git diff` show any change in one of the files?

**Comment by ariel-** [comment]
https://mega.nz/#!MsdhiRrJ!At-8UqCBFT6GLoIuPjBpAQRA29-Ulmxy0Gq8xMLGITU

git diff returns to prompt with no output (no changes)

**Comment by DDuarte** [comment]
Well... no ideas.
![](http://i.imgur.com/QeZ1uQJ.png)

The only difference is LF vs CRLF but that should not matter since the way we calculate the file hashes  is immune to that (and this issue would show up a lot earlier if line endings mattered).

**Comment by ariel-** [comment]
Recloned the repo in new folder, same: http://pastebin.com/cPFsccJR

**Comment by tkrokli** [comment]
Will this issue continue to appear if you start with the one of the last commits before TDB 335.60,
for example https://github.com/TrinityCore/TrinityCore/commit/7593e86 , and then update to TDB 335.60? You may want to test it in steps, 1 commit at a time. I still don't understand what triggers this.

**Comment by Naios** [comment]
Could you try to update your OpenSSL version to 1.0.2* ?
````
Using SSL version: OpenSSL 1.0.1e 11 Feb 2013 (library: OpenSSL 1.0.1e-fips 11 Feb 2013)
```

Also let me know your libcxx version:

```c++
#include <cstdio>

int main(int argc, char* argv[]){
#ifdef __GLIBCPP__
    std::printf("GLIBCPP: %d\n",__GLIBCPP__);
#endif
#ifdef __GLIBCXX__
    std::printf("GLIBCXX: %d\n",__GLIBCXX__);
#endif
   return 0;
}
```

Store the snippet above in a file named `version.cpp` and run the following command:

```sh
gcc version.cpp && ./a.out
```

Could you try to build TrinityCore using Clang and libc++ to check whether this issue is caused through your runtime?

**Comment by ariel-** [comment]
`GLIBCXX: 20140120`

**Comment by Naios** [comment]
I wrote a [small testsuite](https://github.com/Naios/TrinityCore/commit/8fdbca74067cbb82ff44429a95cb976c9c172eb5) to identity your issue:

```sh
git remote add naios https://github.com/Naios/TrinityCore.git
git fetch naios
git checkout updater_tests
```

Please build and invoke the `updatechecker` tool, which checks for textmode and hashing issues.

```sh
cmake .. -DTOOLS=1
make updatechecker

./updatechecker
```

**Comment by ariel-** [comment]
```
[ERROR] textmode failed (lf != crlf)
[OK] hashes are equal
[ERROR] The hash is wrong! (B8B17AD613463C3C9A1FE928819FB30CB853E6B1)
```

**Comment by Naios** [comment]
I updated the testcode, could you run it again please?

**Comment by ariel-** [comment]
```
[ERROR] lf file has the wrong content!
(000000000000000000000000000000000000000000000000000000)
[ERROR] textmode failed (lf != crlf)
[OK] hashes are equal
[OK] the file hash is correct
[OK] OpenSSL SHA1 is ok
```

**Comment by Naios** [comment]
Seems like CentOS fails to read the file correctly, in windows all tests are passing and on ubuntu it will look like:
```
[NOTE] crlf file has crlf line endings
[OK] the lf file is ok
(626C75620A313233343536373839300A313233343536373839300A)
[ERROR] textmode failed (lf != crlf)
[OK] hashes are equal
[OK] the file hash is correct
[OK] OpenSSL SHA1 is ok
```

Try to update your gcc toolchain or use clang together with libc++

Also you could try to add the following patch to see whether the updates were read correctly:

```diff
diff --git a/src/server/database/Updater/UpdateFetcher.cpp b/src/server/database/Updater/UpdateFetcher.cpp
index fd0dbdd..8625abb 100644
--- a/src/server/database/Updater/UpdateFetcher.cpp
+++ b/src/server/database/Updater/UpdateFetcher.cpp
@@ -151,6 +151,9 @@ UpdateFetcher::SQLUpdate UpdateFetcher::ReadSQLUpdate(boost::filesystem::path co
 
     in.read(&(*update)[0], update->size());
     in.close();
+
+    TC_LOG_INFO("sql.updates", "%s", update->c_str());
+
     return update;
 }
```

**Comment by ariel-** [comment]
Now clang build fails with
```
/home/trinity/src/src/server/database/Updater/DBUpdater.cpp:
(.text._ZN5boost9iostreams13stream_bufferINS0_22file_descriptor_sourceESt11char_traitsIcESaIcENS0_14input_seekableEE4openERKS2_ll[_ZN5boost9iostreams13stream_bufferINS0_22file_descriptor_sourceESt11char_traitsIcESaIcENS0_14input_seekableEE4openERKS2_ll]+0xa2):
undefined reference to `std::ios_base::failure::failure(char const*, std::error_code const&)'
```

(I have compiled both gcc 5.3 and clang 3.7.1 from source)

Seems related to #15751

**Comment by ariel-** [comment]
Unfortunately, building boost with clang still get the same link errors. Any ideas so I can test this with clang?

**Comment by Naios** [comment]
No not really, you could try to downgrade gcc to 4.9 on your own risk, which still uses the old C++ ABI.

**Comment by ariel-** [comment]
Unfortunately. now it fails compiling with the following, I have already deleted the build folder and ran cmake again... any ideas?

```CMakeFiles/authserver.dir/Main.cpp.o: In function `GetConsoleArguments(int, char**, std::string&, std::string&)':
/home/trinity/src/src/server/authserver/Main.cpp:(.text+0x4a42): undefined reference to `boost::program_options::options_description::options_description(std::
string const&, unsigned int, unsigned int)'
/home/trinity/src/src/server/authserver/Main.cpp:(.text+0x4c6f): undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_optio
ns::options_description const&)'
CMakeFiles/authserver.dir/Main.cpp.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/home/trinity/src/src/server/authserver/Main.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_com
mand_line_parserIcEC2EiPKPKc]+0x4a): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > co
nst&)'
CMakeFiles/authserver.dir/Main.cpp.o: In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<
std::string> > const&) const':
/home/trinity/src/src/server/authserver/Main.cpp:(.text._ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program
_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x3d): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string,
 std::allocator<std::string> > const&, std::string*, int)'
CMakeFiles/authserver.dir/Main.cpp.o: In function `std::vector<std::string, std::allocator<std::string> > boost::program_options::to_internal<std::string>(std::vector<
std::string, std::allocator<std::string> > const&)':
/home/trinity/src/src/server/authserver/Main.cpp:(.text._ZN5boost15program_options11to_internalISsEESt6vectorISsSaISsEERKS2_IT_SaIS5_EE[_ZN5boost15program_opti
ons11to_internalISsEESt6vectorISsSaISsEERKS2_IT_SaIS5_EE]+0x88): undefined reference to `boost::program_options::to_internal(std::string const&)'
CMakeFiles/authserver.dir/Main.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x40): undefined referen
ce to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
../database/libdatabase.a(DBUpdater.cpp.o): In function `boost::iostreams::file_descriptor_source::file_descriptor_source<boost::filesystem::path>(boost::filesystem::p
ath const&, std::_Ios_Openmode)':
/home/trinity/src/src/server/database/Updater/DBUpdater.cpp:(.text._ZN5boost9iostreams22file_descriptor_sourceC2INS_10filesystem4pathEEERKT_St13_Ios_Openmode[_
ZN5boost9iostreams22file_descriptor_sourceC2INS_10filesystem4pathEEERKT_St13_Ios_Openmode]+0x31): undefined reference to `boost::iostreams::file_descriptor_source::ope
n(boost::iostreams::detail::path const&, std::_Ios_Openmode)'
../database/libdatabase.a(DBUpdater.cpp.o): In function `boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_source, std::char_traits<char>,
 std::allocator<char>, boost::iostreams::input_seekable>::seekpos(std::fpos<__mbstate_t>, std::_Ios_Openmode)':
/home/trinity/src/src/server/database/Updater/DBUpdater.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsI
cESaIcENS0_14input_seekableEE7seekposESt4fposI11__mbstate_tESt13_Ios_Openmode[_ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_trai
tsIcESaIcENS0_14input_seekableEE7seekposESt4fposI11__mbstate_tESt13_Ios_Openmode]+0x3a): undefined reference to `boost::iostreams::file_descriptor::seek(long, std::_Io
s_Seekdir)'
../database/libdatabase.a(DBUpdater.cpp.o): In function `boost::iostreams::detail::indirect_streambuf<boost::iostreams::file_descriptor_source, std::char_traits<char>,
 std::allocator<char>, boost::iostreams::input_seekable>::seek_impl(long, std::_Ios_Seekdir, std::_Ios_Openmode)':
/home/trinity/src/src/server/database/Updater/DBUpdater.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsI
cESaIcENS0_14input_seekableEE9seek_implElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsI
cESaIcENS0_14input_seekableEE9seek_implElSt12_Ios_SeekdirSt13_Ios_Openmode]+0x7c): undefined reference to `boost::iostreams::file_descriptor::seek(long, std::_Ios_Seek
dir)'
/home/trinity/src/src/server/database/Updater/DBUpdater.cpp:(.text._ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsI
cESaIcENS0_14input_seekableEE9seek_implElSt12_Ios_SeekdirSt13_Ios_Openmode[_ZN5boost9iostreams6detail18indirect_streambufINS0_22file_descriptor_sourceESt11char_traitsI
cESaIcENS0_14input_seekableEE9seek_implElSt12_Ios_SeekdirSt13_Ios_Openmode]+0x96): undefined reference to `boost::iostreams::file_descriptor::seek(long, std::_Ios_Seek
dir)'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/authserver/authserver] Error 1
make[1]: *** [src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Naios** [comment]
Did you rebuild boost with clang?

**Comment by ariel-** [comment]
Yes, using gcc 4.9 and clang 3.7, boost built with clang. Cmake detects boost correctly.

**Comment by Naios** [comment]
No ideas then, maybe you can get help at #15751.
All in all the linking issues aren't related to this ticket.

Did you try to apply the patch which I've posted?

**Comment by ariel-** [comment]
Update: I rebuilt boost with GCC 4.9, server built with Clang 3.7.1, now links properly.

updatechecker output:
```
[NOTE] crlf file has crlf line endings
[OK] the lf file is ok
(626C75620A313233343536373839300A313233343536373839300A)
[ERROR] textmode failed (lf != crlf)
[OK] hashes are equal
[OK] the file hash is correct
[OK] OpenSSL SHA1 is ok
```

Worldserver output (patch applied): https://gist.github.com/ariel-/75cf4d0850309a81ad8a

**Comment by tkrokli** [comment]
Your worldserver output looks unneccessary long. I can't remember seeing SQL shown in my consoles.

**Comment by ariel-** [comment]
@tkrokli: https://github.com/TrinityCore/TrinityCore/issues/16209#issuecomment-173201981

**Comment by Naios** [comment]
Alright, seems like it was a bug caused through your build environment.

**Comment by ariel-** [comment]
Well, looks like I will need to use it without autoupdater after all, even with expected output from checker it insists on applying archived sqls.

**Comment by Naios** [comment]
Did you clean your world database?
The updatechecker output is correct,
it should work like it's intended.

**Comment by ariel-** [comment]
Yup. I reimported full TDB 335.60

**Comment by Naios** [comment]
Did you clone the source directly to your cent os machine?
Is it possible that the updates contain any CRLF (windows) line endings?

**Comment by DDuarte** [comment]
"Applying of file '/home/trinity/src/sql/old/3.3.5a/world/59_2015_11_07/2015_07_19_00_world_2015_07_18_04.sql'"

That doesn't happen when your base file is 335.59 or higher...

**Comment by tkrokli** [comment]
I imagine that the only way I could replicate this issue (reapplying old SQLs and TDB) would be if both TDB 335.59 and all of its updates were available in my cloned source code tree. I can't see how this issue would occur if the full TDB 335.59 and its updates were not available in my cloned source, only 335.60.
(I would have tested this theory now if I was not already busy fixing 2 of my own PRs at the moment.)

**Comment by Aokromes** [comment]
Btw, any reason to use 6.7 instead 7.0?

**Comment by Aokromes** [comment]
Tried myself CentOS 7...

http://pastebin.com/iTTJmsLn

**Comment by pete318** [comment]
Meanwhile I tried 6.7 and interestingly same problem, but different sha sum values.

http://pastebin.com/hQrFBDxQ

GCC:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-2/root/usr --mandir=/opt/rh/devtoolset-2/root/usr/share/man --infodir=/opt/rh/devtoolset-2/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --with-mpc=/dev/shm/home/centos/rpm/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
```

Boost: 1.60.0

Correct result from sha1sum
```
sha1sum ../../3.3.5/sql/old/3.3.5a/world/59_2015_11_07/2015_07_14_00_world.sql
70fac1e2f1dd5a0d97a033305946eb5cc8013038  ../../3.3.5/sql/old/3.3.5a/world/59_2015_11_07/2015_07_14_00_world.sql
```

So, some strange library combination is causing the hashes to be calculated incorrectly it seems.

**Comment by pete318** [comment]
So, here's what worked for me:

```Diff
--- a/src/server/database/Updater/UpdateFetcher.cpp
+++ b/src/server/database/Updater/UpdateFetcher.cpp
@@ -142,10 +142,9 @@ UpdateFetcher::SQLUpdate UpdateFetcher::ReadSQLUpdate(boost::filesystem::path co
     std::ifstream in(file.c_str());
     WPFatal(in.is_open(), "Could not read an update file.");

-    auto const start_pos = in.tellg();
-    in.ignore(std::numeric_limits<std::streamsize>::max());
-    auto const char_count = in.gcount();
-    in.seekg(start_pos);
+    in.seekg(0, in.end);
+    int const char_count = in.tellg();
+    in.seekg(0, in.beg);

     SQLUpdate const update(new std::string(char_count, char{}));
```

No idea why it only causes a problem for Centos though.

**Comment by Shauren** [comment]
just use boost::filesystem::file_size

**Comment by ariel-** [comment]
So there was an issue with the OS, rather than something local to my config,

Meanwhile I need to fix a link error that appeared after openssl update
```
/usr/local/bin/ld: /usr/local/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/local/lib/libdl.so.2: error adding symbols: DSO missing from command line
```

I compiled glibc from source too

**Comment by pete318** [comment]
> So there was an issue with the OS, rather than something local to my config,

Yes, it's some peculiarity with how the std::ifstream was used, that wasn't working with Centos 6.7. Applying the change I made, just adjusts how it ascertains the length of the file. I have an idea exactly what is going on. But, I don't think it's worth proving. The solution is right there.

If you're able to upgrade though, I would suggest it. Quite some old packages on there, and needed to manually compile and/or upgrade a few things just to make it compile.

**Comment by ariel-** [comment]
Interesting... on windows boost::filesystem::file_size returns one more than the ignore-count method, this null termination is what changes the hash

**Comment by pete318** [comment]
> Interesting... on windows boost::filesystem::file_size returns one more than the ignore-count method, this null termination is what changes the hash

Not quite. The ignore/count method was actually causing the file not to be read at all. My thinking is that on Centos it's behaving like C++98. It's clearly not all that way since there's a fair bit of C++11 code in TC now. But, here's what I think was happening.

```C++
    auto const start_pos = in.tellg();
    in.ignore(std::numeric_limits<std::streamsize>::max());
    auto const char_count = in.gcount();
    in.seekg(start_pos);
```
So, the first tellg works ok. Should return 0. That's fine. Then the ignore sends it beyond the eof (and it'd stop reading at the eof). gcount correctly sets the count to read. But seekg has a c++11 functionality where it will clear the eof flag if moved away from eof. c++98 will "fail" and I suspect this leaves the pointer at the end of the file.

http://www.cplusplus.com/reference/istream/istream/seekg/

So, an attempt to read returns an empty buffer, with the length of the file.

That's what I think is happening anyway. The change I suggested just changes the way the length is obtained without setting the eof flag and hence the position is returned to the beginning fine.

**Comment by Shauren** [comment]
Apparently ignore is better because of some weirdness i cant even remember at this point
What if you just called ```in.clear(std::ios_base::eofbit);?```

**Comment by ariel-** [comment]
The updates where read correctly, see log in this comment: https://github.com/TrinityCore/TrinityCore/issues/16209#issuecomment-175938168

However there is the issue of this 'extra' null character at the end of the file which causes hash change.

**Comment by pete318** [comment]
Extra hash change? I tried it on Centos 6.7, with the change above it works. Now, as to whether in.clear would be a better solution I can check that too. If EC2 spot price is still good :P

**Comment by pete318** [comment]
> What if you just called in.clear(std::ios_base::eofbit);

Almost, clear actually doesn't work how it seems it should

http://www.cplusplus.com/reference/ios/ios/clear/

It actually sets the flags to an absolute state, the default being good (and all others false). So just in.clear(); does it. Right after the ignore.

**Comment by Shauren** [comment]
@pete318 it seems i updated my comment while you were posting, ```in.clear(in.rdstate()&~std::ios_base::eofbit);``` - we only want to clear eof, not other failure flags

**Comment by pete318** [comment]
Yep that will work fine, well assuming it doesn't require the "good" bit to be set. 

That naming of the flag functions are a bit crappy though.

clear you would expect to either clear all or selected flags.
setstate you'd expect to set/clear selected flags. But it's nothing like that.

clear sets an absolute mask and setstate sets an or mask. Not very clear at all.

**Comment by ariel-** [comment]
Confirm, clearing stream eof bit solves the issue in CentOS, without breaking other platforms. :+1:

**Comment by Naios** [comment]
@pete318 your change looks good, could you push it?

**Comment by Warpten** [comment]
Why not just use std::ios_base::ate ?

**Comment by Naios** [comment]
I stumbled over an interesting link abouting seeking and textmode streams: https://www.securecoding.cert.org/confluence/display/c/FIO19-C.+Do+not+use+fseek()+and+ftell()+to+compute+the+size+of+a+regular+file

Maybe we could replace the whole reading mechanism to a non seeking one:

```c++
 SQLUpdate update = Trinity::make_unique<std::string>(
     std::istreambuf_iterator<char>(in),
      std::istreambuf_iterator<char>());
```

**Comment by DDuarte** [comment]
indi from #c++ @ Rizon wrote a blog post about reading files to memory in C++
http://cpp.indi.frih.net/blog/2014/09/how-to-read-an-entire-file-into-memory-in-cpp/

**Comment by pete318** [comment]
> @pete318 your change looks good, could you push it?

I didn't see this until now. I'll see if I can tomorrow.

**Comment by Naios** [comment]
Yep, you suggested the blog post 1 Year ago.
Probably it's the best to move to the easier solution mentioned in the blog:

```c++
auto s = [&in]{
  std::ostringstream ss{};
  ss << in.rdbuf();
  return ss.str();
}();
```

@pete318 Wait... maybe we could use the code snipped mentioned above, since we aren't reading that huge files anyway.
