### ISSUE TITLE
Linker problem: undefined reference to `__muloti4'

### ISSUE THREAD

**Issue by mweinelt** [TrinityCore/TrinityCore#25582]
**Description:**

I noticed a linker problem since TDB335.20091:

```
[100%] Linking CXX executable worldserver
/nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: ../scripts/libscripts.a(cs_gobject.cpp.o): in function `_ZSt10from_charsImENSt9enable_ifIXsr22__is_int_to_chars_typeIT_EE5valueESt17from_chars_resultE4typeEPKcS6_RS1_i':
cs_gobject.cpp:(.text._ZSt10from_charsImENSt9enable_ifIXsr22__is_int_to_chars_typeIT_EE5valueESt17from_chars_resultE4typeEPKcS6_RS1_i[_ZSt10from_charsImENSt9enable_ifIXsr22__is_int_to_chars_typeIT_EE5valueESt17from_chars_resultE4typeEPKcS6_RS1_i]+0xce): undefined reference to `__muloti4'
/nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: cs_gobject.cpp:(.text._ZSt10from_charsImENSt9enable_ifIXsr22__is_int_to_chars_typeIT_EE5valueESt17from_chars_resultE4typeEPKcS6_RS1_i[_ZSt10from_charsImENSt9enable_ifIXsr22__is_int_to_chars_typeIT_EE5valueESt17from_chars_resultE4typeEPKcS6_RS1_i]+0x1aa): undefined reference to `__muloti4'
/nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: ../game/libgame.a(Channel.cpp.o): in function `Channel::Channel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Channel.cpp:(.text+0x468): undefined reference to `__muloti4'
/nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: ../game/libgame.a(HyperlinkTags.cpp.o): in function `bool HyperlinkDataTokenizer::TryConsumeTo<ObjectGuid>(ObjectGuid&)':
HyperlinkTags.cpp:(.text._ZN22HyperlinkDataTokenizer12TryConsumeToI10ObjectGuidEEbRT_[_ZN22HyperlinkDataTokenizer12TryConsumeToI10ObjectGuidEEbRT_]+0xd4): undefined reference to `__muloti4'
/nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: HyperlinkTags.cpp:(.text._ZN22HyperlinkDataTokenizer12TryConsumeToI10ObjectGuidEEbRT_[_ZN22HyperlinkDataTokenizer12TryConsumeToI10ObjectGuidEEbRT_]+0x1d1): undefined reference to `__muloti4'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:193: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1347: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

I bisected the failing build between TDB335.20081 and 20091 to the following commit:

```
cd30e0b86ce6ee88386a91cebdf353fc55805c57 is the first bad commit                      
commit cd30e0b86ce6ee88386a91cebdf353fc55805c57                                       
Author: Treeston <treeston.mmoc@gmail.com>                                            
Date:   Wed Aug 26 23:31:45 2020 +0200                                                
                                                                                      
    Common/Utilities: Centralize string -> T conversion in StringConvert.h (PR #25335)
                                                                                      
 cmake/compiler/clang/settings.cmake                |  25 +++                         
 src/common/Configuration/Config.cpp                |  11 +-                          
 src/common/Utilities/StringConvert.h               | 179 +++++++++++++++++++++       
 src/common/Utilities/Util.cpp                      |   5 -                           
 src/common/Utilities/Util.h                        |  12 +-                          
 .../game/Chat/ChatCommands/ChatCommandArgs.h       |  15 +-                          
 src/server/game/Chat/Hyperlinks.h                  |  31 ++--                        
 7 files changed, 243 insertions(+), 35 deletions(-)                                  
 create mode 100644 src/common/Utilities/StringConvert.h                              
bisect run success                                                                    
```

**Expected behaviour:**

Linker shouldn't fail.

**Steps to reproduce the problem:**

1. Build the worldserver

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

cd30e0b86ce6ee88386a91cebdf353fc55805c57

**Operating system:** NixOS Unstable (https://github.com/mweinelt/nur-packages/blob/master/pkgs/servers/games/trinitycore/default.nix)

cmake 3.18.2
clang 7.1.0
boost 1.69.0

**Comment by Shauren** [comment]
Seen before, the short version is that clang 7 doesn't really work, use a different version

**Comment by mweinelt** [comment]
Thanks, I will. One excerpt from the configure phase:

```
-- Clang: Minimum version required is 7.0.0, found 7.1.0 - ok!
```

That should probably be updated.

**Comment by Shauren** [comment]
We have some workarounds for 7.0 exactly for this issue but it looks like they aren't working

**Comment by mweinelt** [comment]
Moved to 11.0.0 and LGTM. Thanks for the quick help
