### PR TITLE
Fix build on GCC 7.1.

### LINKED ISSUE #19859: Core/Battlefield: gcc 7.1.1 does not compile without errors, Build fix needed
**Description:** Doesn't compile with GCC 7.1.1

**Current behaviour:**

```
[ 99%] Built target scripts_northrend
[100%] Linking CXX executable worldserver
../game/libgame.so: undefined reference to `Trinity::PlayerListSearcher<Trinity::AnyPlayerInObjectRangeCheck>::Visit(GridRefManager<Player>&)'
make[1]: *** [CMakeFiles/Makefile2:2339: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 1
make: *** [Makefile:130: all] Error 1
```
**Branch(es):** 3.3.5

**TC rev. hash/commit:**  TrinityCore revision   : 1660bb7d27d6 2017-06-07 02:33:47 +0200 (3.3.5 branch)

**TDB version:** TDB 335.63 with updates.

**Operating system:** Arch Linux

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #19859

### CODE REVIEW

**Comment by Aokromes** [comment]
4.7? sorry that gcc version is under the minimum supported.

**Comment by Infernales** [comment]
@Aokromes This line is present in this file in the master branch. In the 3.3.5 branch, you missed it in this file.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/ede8f0ca0a28d059c1356c6970ac87f53c72a424/cmake/compiler/gcc/settings.cmake

**Comment by Infernales** [comment]
Sorry, I confused the GCC version in PR.
